"""add client contact_emails

Revision ID: 403de93ef919
Revises: 885b0b21eecb
Create Date: 2026-06-01 12:24:25.746933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403de93ef919'
down_revision: Union[str, None] = '885b0b21eecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add NOT NULL with a temporary default to backfill existing rows, then drop
    # the default so the column matches the model (app provides [] on insert).
    op.add_column(
        "clients",
        sa.Column("contact_emails", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.execute("ALTER TABLE clients ALTER COLUMN contact_emails DROP DEFAULT")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'contact_emails')
    # ### end Alembic commands ###
