"""initial schema

Revision ID: e8a046fe7204
Revises: 
Create Date: 2026-05-30 14:54:09.433294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e8a046fe7204'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")   
    op.create_table('agencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('slack_channel_ids', sa.JSON(), nullable=False),
    sa.Column('jira_project_keys', sa.JSON(), nullable=False),
    sa.Column('drive_folder_ids', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_client_id'), 'alerts', ['client_id'], unique=False)
    op.create_table('data_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_chunks_client_id'), 'data_chunks', ['client_id'], unique=False)
    op.create_index(op.f('ix_data_chunks_source_timestamp'), 'data_chunks', ['source_timestamp'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_client_id'), 'summaries', ['client_id'], unique=False)
    op.create_index(op.f('ix_summaries_generated_at'), 'summaries', ['generated_at'], unique=False)
    op.execute(                                            # <-- add as LAST line
        "CREATE INDEX data_chunks_embedding_idx "
        "ON data_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS data_chunks_embedding_idx")
    op.drop_index(op.f('ix_summaries_generated_at'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_client_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_data_chunks_source_timestamp'), table_name='data_chunks')
    op.drop_index(op.f('ix_data_chunks_client_id'), table_name='data_chunks')
    op.drop_table('data_chunks')
    op.drop_index(op.f('ix_alerts_client_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('integrations')
    op.drop_table('clients')
    op.drop_table('agencies')
    # ### end Alembic commands ###
