"""add audit_logs table

Revision ID: f525f5929eea
Revises: d4e5f6a7b8c9
Create Date: 2026-06-11 09:40:44.156914

Append-only trail of who read which client's (third-party) data. Writes run on the
owner role (bypasses RLS, see core/audit.py); reads run on the restricted app_user
role on the API path, so the table gets an agency-scoped, OWNER-ONLY RLS policy
(members never see the agency's audit trail — same posture as integrations). The
endpoint is additionally owner-gated in routers/activity.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f525f5929eea'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_AGENCY = "current_setting('app.current_agency_id', true)"
_IS_OWNER = "nullif(current_setting('app.current_member_id', true), '') IS NULL"
_AUDIT_VISIBLE = f"agency_id = {_AGENCY} AND {_IS_OWNER}"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('actor_member_id', sa.String(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_member_id'), 'audit_logs', ['actor_member_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_agency_id'), 'audit_logs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_client_id'), 'audit_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###

    # restricted API role: read its own trail + insert (writes also go via owner role)
    op.execute("GRANT SELECT, INSERT ON audit_logs TO app_user")

    # RLS: owner-only, agency-scoped. app_user has no UPDATE/DELETE grant, so the
    # trail is effectively append-only on the request path.
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY audit_logs_owner_isolation ON audit_logs FOR ALL "
        f"USING ({_AUDIT_VISIBLE}) WITH CHECK ({_AUDIT_VISIBLE})"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS audit_logs_owner_isolation ON audit_logs")
    op.execute("ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE SELECT, INSERT ON audit_logs FROM app_user")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_client_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agency_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_member_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
